DECLARE
    v_CIF_CODE VARCHAR2(50) := '7208956674';
    v_INVESTOR_ID NUMBER;
    v_SALE_ID NUMBER;
    v_USER_ID NUMBER;
    v_SALE_REFERRAL_CODE VARCHAR2(50);
    v_INVESTOR_GROUP_ID NUMBER;
BEGIN  
    --Tìm Investor
    BEGIN
        SELECT I.INVESTOR_ID, I.REFERRAL_CODE_SELF INTO v_INVESTOR_ID, v_SALE_REFERRAL_CODE 
        FROM EP_INVESTOR i
        join EP_CIF_CODE cc on i.investor_id = cc.investor_id
        WHERE cc.CIF_CODE = v_CIF_CODE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Không tìm thấy investor bằng cif code' || v_CIF_CODE );
    END;
    
    --xoá thật và tạm
    DELETE EP_INVESTOR WHERE INVESTOR_ID = v_INVESTOR_ID;
    DELETE EP_INVESTOR_TEMP WHERE INVESTOR_GROUP_ID = v_INVESTOR_GROUP_ID;
   
    --TABLE EP_INVESTOR
    DELETE FROM EP_INVESTOR WHERE INVESTOR_ID = v_INVESTOR_ID;
   
    --TABLE EP_INVESTOR_ASSET
    DELETE FROM EP_INVESTOR_ASSET WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_BANK_ACCOUNT
    DELETE FROM EP_INVESTOR_BANK_ACCOUNT WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_BANK_ACCOUNT_TEMP
    DELETE FROM EP_INVESTOR_BANK_ACCOUNT_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_CONTACT_ADD_TEMP
    DELETE FROM EP_INVESTOR_CONTACT_ADD_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_CONTACT_ADDRESS
    DELETE FROM EP_INVESTOR_CONTACT_ADDRESS WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_ID_TEMP
    DELETE FROM EP_INVESTOR_ID_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_IDENTIFICATION
    DELETE FROM EP_INVESTOR_IDENTIFICATION WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_PROF_FILE
    DELETE FROM EP_INVESTOR_PROF_FILE WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_SALE
    DELETE FROM EP_INVESTOR_SALE WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_TEMP
    DELETE FROM EP_INVESTOR_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_TRADING_PROVIDER
    DELETE FROM EP_INVESTOR_TRADING_PROVIDER WHERE INVESTOR_ID = v_INVESTOR_ID;
   
    --Users
    BEGIN
        SELECT USER_ID INTO v_USER_ID 
        FROM USERS 
        WHERE INVESTOR_ID = v_INVESTOR_ID AND ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Không tìm thấy USERS');
    END;
    
    --ACCOUNT USERS
    --TABLE USERS
    DELETE FROM USERS WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    DELETE FROM USERS WHERE USER_ID = v_USER_ID;
    
    --TABLE USERS_CHAT_ROOM
    DELETE FROM USERS_CHAT_ROOM WHERE USER_ID = v_USER_ID;
    
    --TABLE EP_AUTH_OTP
    DELETE FROM EP_AUTH_OTP WHERE USER_ID = v_USER_ID;
    
    --CIF_CODE
    DELETE FROM EP_CIF_CODE WHERE INVESTOR_ID = v_INVESTOR_ID;
   	
    --ORDER
    --TABLE EP_BOND_ORDER_PAYMENT
    DELETE FROM EP_BOND_ORDER_PAYMENT a
    WHERE a.ORDER_ID IN (SELECT b.ORDER_ID FROM EP_BOND_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_BOND_RENEWALS_REQUEST
    DELETE FROM EP_BOND_RENEWALS_REQUEST a
    WHERE a.ORDER_ID IN (SELECT b.ORDER_ID FROM EP_BOND_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_BOND_SECONDARY_CONTRACT
    DELETE FROM EP_BOND_SECONDARY_CONTRACT a
    WHERE a.ORDER_ID IN (SELECT b.ORDER_ID FROM EP_BOND_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_BOND_INTEREST_PAYMENT
    DELETE FROM EP_BOND_INTEREST_PAYMENT a
    WHERE a.ORDER_ID IN (SELECT b.ORDER_ID FROM EP_BOND_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_BOND_INTEREST_PAYMENT_DATE
    DELETE FROM EP_BOND_INTEREST_PAYMENT_DATE a
    WHERE a.ORDER_ID IN (SELECT b.ORDER_ID FROM EP_BOND_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_BOND_ORDER
    DELETE FROM EP_BOND_ORDER WHERE CIF_CODE = v_CIF_CODE;
    
    --TABLE EP_INV_ORDER_CONTRACT_FILE
    DELETE FROM EP_INV_ORDER_CONTRACT_FILE a
    WHERE a.ORDER_ID IN (SELECT b.ID FROM EP_INV_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_INV_INTEREST_PAYMENT
    DELETE FROM EP_INV_INTEREST_PAYMENT a
    WHERE a.ORDER_ID IN (SELECT b.ID FROM EP_INV_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_INV_INTEREST_PAYMENT_DATE
    DELETE FROM EP_INV_INTEREST_PAYMENT_DATE a
    WHERE a.ORDER_ID IN (SELECT b.ID FROM EP_INV_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_INV_RENEWALS_REQUEST
    DELETE FROM EP_INV_RENEWALS_REQUEST a
    WHERE a.ORDER_ID IN (SELECT b.ID FROM EP_INV_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_INV_WITHDRAWAL
    DELETE FROM EP_INV_WITHDRAWAL a
    WHERE a.ORDER_ID IN (SELECT b.ID FROM EP_INV_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_INV_ORDER_PAYMENT
    DELETE FROM EP_INV_ORDER_PAYMENT a
    WHERE a.ORDER_ID IN (SELECT b.ID FROM EP_INV_ORDER b WHERE b.CIF_CODE = v_CIF_CODE);
    
    --TABLE EP_INV_ORDER
    DELETE FROM EP_INV_ORDER WHERE CIF_CODE = v_CIF_CODE;
   
   --Nếu là Sale
    BEGIN
        SELECT SALE_ID INTO v_SALE_ID FROM EP_CORE_SALE WHERE INVESTOR_ID = v_INVESTOR_ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Không tìm thấy SaleId');
    END;
   
    --TABLE EP_CORE_SALE
    DELETE FROM EP_CORE_SALE WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_CORE_SALE_REGISTER
    DELETE FROM EP_CORE_SALE_REGISTER WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_CORE_SALE_TEMP
    DELETE FROM EP_CORE_SALE_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
   
    --TABLE EP_INVESTOR_SALE
    DELETE FROM EP_INVESTOR_SALE WHERE SALE_ID = v_SALE_ID;
    
    --TABLE EP_CORE_SALE_TRADING_PROVIDER
    DELETE FROM EP_CORE_SALE_TRADING_PROVIDER WHERE SALE_ID = v_SALE_ID;
    
    --TABLE EP_CORE_SALE_COLLAB_CONTRACT
    DELETE FROM EP_CORE_SALE_COLLAB_CONTRACT WHERE SALE_ID = v_SALE_ID;
    
    --TABLE EP_CORE_DEPARTMENT_SALE
    DELETE FROM EP_CORE_DEPARTMENT_SALE WHERE SALE_ID = v_SALE_ID;
    
    --INVESTOR LÀ SALE
    DECLARE 
        CURSOR v_DATA_INV_ORDER IS SELECT * FROM EP_INV_ORDER WHERE v_SALE_REFERRAL_CODE IN (SALE_REFERRAL_CODE, SALE_REFERRAL_CODE_SUB);
        CURSOR v_DATA_BOND_ORDER IS SELECT * FROM EP_BOND_ORDER WHERE v_SALE_REFERRAL_CODE IN (SALE_REFERRAL_CODE, SALE_REFERRAL_CODE_SUB);
    BEGIN
        --INV
        FOR v_ORDER IN v_DATA_INV_ORDER LOOP
            
            UPDATE EP_INV_ORDER
            SET SALE_REFERRAL_CODE = NULL
            WHERE v_ORDER.SALE_REFERRAL_CODE = v_SALE_REFERRAL_CODE;
            
            UPDATE EP_INV_ORDER
            SET SALE_REFERRAL_CODE_SUB = NULL
            WHERE v_ORDER.SALE_REFERRAL_CODE_SUB = v_SALE_REFERRAL_CODE;
            
            UPDATE EP_INV_ORDER
            SET SALE_ORDER_ID = NULL
            WHERE v_ORDER.SALE_ORDER_ID = v_SALE_ID;
            
        END LOOP;
        --BOND
        FOR v_ORDER IN v_DATA_BOND_ORDER LOOP
            UPDATE EP_BOND_ORDER
            SET SALE_REFERRAL_CODE = NULL
            WHERE v_ORDER.SALE_REFERRAL_CODE = v_SALE_REFERRAL_CODE;
            
            UPDATE EP_BOND_ORDER
            SET SALE_REFERRAL_CODE_SUB = NULL
            WHERE v_ORDER.SALE_REFERRAL_CODE_SUB = v_SALE_REFERRAL_CODE;
            
            UPDATE EP_BOND_ORDER
            SET SALE_ORDER_ID = NULL
            WHERE v_ORDER.SALE_ORDER_ID = v_SALE_ID;
        END LOOP;
    END;
--    EXCEPTION
--        WHEN OTHERS THEN                     
--            dbms_output.put_line('Generic exception');
END;