DECLARE
    v_PHONE VARCHAR2(50) := '0389102931';
    v_INVESTOR_ID NUMBER;
    v_SALE_ID NUMBER;
    v_USER_ID NUMBER;
    v_CIF_CODE VARCHAR2(50);
    v_SALE_REFERRAL_CODE VARCHAR2(50);
BEGIN  
    --Tìm Investor
    BEGIN
        SELECT INVESTOR_ID, REFERRAL_CODE_SELF INTO v_INVESTOR_ID, v_SALE_REFERRAL_CODE FROM EPIC.EP_INVESTOR WHERE PHONE = v_PHONE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Không tìm thấy investor bằng số điện thoại' || v_PHONE );
    END;
    
    --xoá thật và tạm
    DELETE EPIC.EP_INVESTOR WHERE PHONE = v_PHONE;
    DELETE EPIC.EP_INVESTOR_TEMP WHERE PHONE = v_PHONE;
   
    --TABLE EP_INVESTOR
    DELETE FROM EPIC.EP_INVESTOR WHERE INVESTOR_ID = v_INVESTOR_ID;
   
    --TABLE EP_INVESTOR_ASSET
    DELETE FROM EPIC.EP_INVESTOR_ASSET WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_BANK_ACCOUNT
    DELETE FROM EPIC.EP_INVESTOR_BANK_ACCOUNT WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_BANK_ACCOUNT_TEMP
    DELETE FROM EPIC.EP_INVESTOR_BANK_ACCOUNT_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_CONTACT_ADD_TEMP
    DELETE FROM EPIC.EP_INVESTOR_CONTACT_ADD_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_CONTACT_ADDRESS
    DELETE FROM EPIC.EP_INVESTOR_CONTACT_ADDRESS WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_ID_TEMP
    DELETE FROM EPIC.EP_INVESTOR_ID_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_IDENTIFICATION
    DELETE FROM EPIC.EP_INVESTOR_IDENTIFICATION WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_PROF_FILE
    DELETE FROM EPIC.EP_INVESTOR_PROF_FILE WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_SALE
    DELETE FROM EPIC.EP_INVESTOR_SALE WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_TEMP
    DELETE FROM EPIC.EP_INVESTOR_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_INVESTOR_TRADING_PROVIDER
    DELETE FROM EPIC.EP_INVESTOR_TRADING_PROVIDER WHERE INVESTOR_ID = v_INVESTOR_ID;
   
    --Users
    BEGIN
        SELECT USER_ID INTO v_USER_ID FROM EPIC.USERS WHERE USERNAME = v_PHONE AND ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Không tìm thấy USERS');
    END;
    
    --ACCOUNT USERS
    --TABLE USERS
    DELETE FROM EPIC.USERS WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    DELETE FROM EPIC.USERS WHERE USER_ID = v_USER_ID;
    
    --TABLE USERS_CHAT_ROOM
    DELETE FROM EPIC.USERS_CHAT_ROOM WHERE USER_ID = v_USER_ID;
    
    --TABLE EP_AUTH_OTP
    DELETE FROM EPIC.EP_AUTH_OTP WHERE USER_ID = v_USER_ID;
    
    --CIF_CODE
    DELETE FROM EPIC.EP_CIF_CODE WHERE INVESTOR_ID = v_INVESTOR_ID;
   
    --Tìm CifCode
    BEGIN
        SELECT CIF_CODE INTO v_CIF_CODE FROM EPIC.EP_CIF_CODE WHERE INVESTOR_ID = v_INVESTOR_ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Không tìm thấy CifCode');
    END;
    
    --TABLE EP_INV_ORDER
    DELETE FROM EPIC.EP_INV_ORDER WHERE CIF_CODE = v_CIF_CODE;
   
   --Nếu là Sale
    BEGIN
        SELECT SALE_ID INTO v_SALE_ID FROM EPIC.EP_CORE_SALE WHERE INVESTOR_ID = v_INVESTOR_ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Không tìm thấy SaleId');
    END;
   
    --TABLE EP_CORE_SALE
    DELETE FROM EPIC.EP_CORE_SALE WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_CORE_SALE_REGISTER
    DELETE FROM EPIC.EP_CORE_SALE_REGISTER WHERE INVESTOR_ID = v_INVESTOR_ID;
    
    --TABLE EP_CORE_SALE_TEMP
    DELETE FROM EPIC.EP_CORE_SALE_TEMP WHERE INVESTOR_ID = v_INVESTOR_ID;
   
    --TABLE EP_INVESTOR_SALE
    DELETE FROM EPIC.EP_INVESTOR_SALE WHERE SALE_ID = v_SALE_ID;
    
    --TABLE EP_CORE_SALE_TRADING_PROVIDER
    DELETE FROM EPIC.EP_CORE_SALE_TRADING_PROVIDER WHERE SALE_ID = v_SALE_ID;
    
    --TABLE EP_CORE_SALE_COLLAB_CONTRACT
    DELETE FROM EPIC.EP_CORE_SALE_COLLAB_CONTRACT WHERE SALE_ID = v_SALE_ID;
    
    --TABLE EP_CORE_DEPARTMENT_SALE
    DELETE FROM EPIC.EP_CORE_DEPARTMENT_SALE WHERE SALE_ID = v_SALE_ID;
    
    --INVESTOR LÀ SALE
    -- DECLARE 
    --     CURSOR v_DATA_INV_ORDER IS SELECT * FROM EP_INV_ORDER WHERE v_SALE_REFERRAL_CODE IN (SALE_REFERRAL_CODE, SALE_REFERRAL_CODE_SUB) AND v_SALE_REFERRAL_CODE IS NOT NULL;
    --     CURSOR v_DATA_BOND_ORDER IS SELECT * FROM EP_BOND_ORDER WHERE v_SALE_REFERRAL_CODE IN (SALE_REFERRAL_CODE, SALE_REFERRAL_CODE_SUB) AND v_SALE_REFERRAL_CODE IS NOT NULL;
    -- BEGIN
    --     --INV
    --     FOR v_ORDER IN v_DATA_INV_ORDER LOOP
            
    --         UPDATE EP_INV_ORDER
    --         SET SALE_REFERRAL_CODE = NULL
    --         WHERE v_ORDER.SALE_REFERRAL_CODE = v_SALE_REFERRAL_CODE;
            
    --         UPDATE EP_INV_ORDER
    --         SET SALE_REFERRAL_CODE_SUB = NULL
    --         WHERE v_ORDER.SALE_REFERRAL_CODE_SUB = v_SALE_REFERRAL_CODE;
            
    --         UPDATE EP_INV_ORDER
    --         SET SALE_ORDER_ID = NULL
    --         WHERE v_ORDER.SALE_ORDER_ID = v_SALE_ID;
            
    --     END LOOP;
    --     --BOND
    --     FOR v_ORDER IN v_DATA_BOND_ORDER LOOP
    --         UPDATE EP_BOND_ORDER
    --         SET SALE_REFERRAL_CODE = NULL
    --         WHERE v_ORDER.SALE_REFERRAL_CODE = v_SALE_REFERRAL_CODE;
            
    --         UPDATE EP_BOND_ORDER
    --         SET SALE_REFERRAL_CODE_SUB = NULL
    --         WHERE v_ORDER.SALE_REFERRAL_CODE_SUB = v_SALE_REFERRAL_CODE;
            
    --         UPDATE EP_BOND_ORDER
    --         SET SALE_ORDER_ID = NULL
    --         WHERE v_ORDER.SALE_ORDER_ID = v_SALE_ID;
    --     END LOOP;
    -- END;
--    EXCEPTION
--        WHEN OTHERS THEN                     
--            dbms_output.put_line('Generic exception');
END;