alter session set "_ORACLE_SCRIPT"=true;

-- function
GRANT ALL PRIVILEGES ON GET_SEQ TO EPIC_COMPANY_SHARES;
GRANT ALL PRIVILEGES ON SP_THROW_EXCEPTION TO EPIC_COMPANY_SHARES;
GRANT ALL PRIVILEGES ON FUNC_GET_DEF_ERROR TO EPIC_COMPANY_SHARES;
GRANT ALL PRIVILEGES ON FUNC_GET_DEFCODE TO EPIC_COMPANY_SHARES;

GRANT ALL PRIVILEGES ON EP_TRADING_PROVIDER TO EPIC_COMPANY_SHARES;
GRANT ALL PRIVILEGES ON FUNC_IS_WEEKEND TO EPIC_COMPANY_SHARES;


--FUNCTION EPIC_GARNER;
GRANT ALL PRIVILEGES ON GET_SEQ TO EPIC_GARNER;
GRANT ALL PRIVILEGES ON SP_THROW_EXCEPTION TO EPIC_GARNER;
GRANT ALL PRIVILEGES ON FUNC_GET_DEF_ERROR TO EPIC_GARNER;
GRANT ALL PRIVILEGES ON EP_TRADING_PROVIDER TO EPIC_GARNER;
GRANT ALL PRIVILEGES ON FUNC_IS_WEEKEND TO EPIC_GARNER;

-- các bảng
GRANT ALL PRIVILEGES ON DEFERROR TO EPIC_COMPANY_SHARES;
GRANT ALL PRIVILEGES ON EP_AUTH_OTP TO EPIC_COMPANY_SHARES;
GRANT ALL PRIVILEGES ON EP_CIF_CODE TO EPIC_COMPANY_SHARES;
GRANT ALL PRIVILEGES ON EP_ISSUER TO EPIC_COMPANY_SHARES;

--Các bảng cho EPIC_GARNER
GRANT ALL PRIVILEGES ON USERS TO EPIC_GARNER;
GRANT ALL PRIVILEGES ON USERS TO EPIC;
--GRANT DBA TO EPIC_GARNER;

--PACKAGE
GRANT ALL PRIVILEGES ON PKG_DATA TO EPIC_COMPANY_SHARES;
GRANT ALL PRIVILEGES ON PKG_DATA TO EPIC;

GRANT UNLIMITED TABLESPACE TO EPIC_COMPANY_SHARES;
GRANT UNLIMITED TABLESPACE TO EPIC;