using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EPIC.Utils
{
    public enum ErrorCode
    {
        System = 101,

        NotFound = 1404,
        BadRequest = 1400,

        InternalServerError = 1500,
        /// <summary>
        /// Danh cho các lỗi về http request
        /// </summary>
        HttpRequestException = 1501,
        NotHaveClaim = 1502,
        DbUpdateException = 1503,
        GetRequestService = 1504,
        /// <summary>
        /// Request timeout sang bên thứ 3
        /// </summary>
        HttpRequestTimeOut = 1505,
        /// <summary>
        /// lỗi logic api bên thứ 3
        /// </summary>
        HttpRequestThirdPartDomainError = 1506,

        ///user
        UserUsernameDuplicated = 1001,
        UserNotFound = 1002,
        UserDeactive = 1003,
        UserInvalidPasword = 1004,
        UserLoginFailMax = 1005,
        UserInvalidOldPasword = 1006,
        UserInvestorIdNotFound = 1007,
        UserIsNotIsTempPassword = 1008,
        UserNewPasswordSameOldPassword = 1009,
        UserIsDeactive = 1010,
        UserFcmTokenNotExists = 1030,
        UserInvalid = 1031,
        UserInvalidPinCode = 1032,
        UserIsLocked = 1033,
        UserInvestorCanNotLoginCMS = 1034,
        UserLoginWithAdminFailed = 1042,

        //investor
        InvestorNotFound = 2001,
        InvestorInterestNotFound = 2002,
        InvestorHasNotAccount = 2003,
        InvestorEmalOrPhoneNotRegis = 2004,
        InvestorResetPasswordTokenInvalid = 2005,
        InvestorResetPasswordTokenExpire = 2006,
        InvestorNotActive = 2007,
        InvestorInvalidPin = 2008,
        InvestorInvalidOldPin = 2009,
        InvestorContractNotFound = 2010,
        InvestorErrorOCRBackId = 2011,
        InvestorErrorOCRPassport = 2012,
        InvestorErrorFaceMatch = 2013,
        InvestorOTPInvalid = 2014,
        InvestorOTPExpire = 2015,
        InvestorFaceRecognitionNotMatch = 2016,
        InvestorFaceRecognitionNoFaceDetected = 2017,
        InvestorVerifyCodeInvalid = 2018,
        InvestorVerifyCodeExpire = 2019,
        InvestorErrorOCRDifference = 2020,
        InvestorNotFoundOTP = 2021,
        InvestorEKYCNotFound = 2022,
        InvestorIdInUsers = 2023,
        InvestorIdentificationTypeExisted = 2024,
        InvestorApproveNotFound = 2025,
        InvestorIdentificationNotFound = 2026,
        InvestorEmailExisted = 2027,
        InvestorPhoneExisted = 2028,
        InvestorIdTypeExisted = 2029,
        InvestorIdNoExisted = 2030,
        InvestorCreateUserNotPhone = 2031,
        InvestorDeactive = 2032,
        InvestorCreateUserNotEmail = 2033,
        InvestorBankIsRegistered = 2034,
        InvestorPendingRequest = 2035,
        InvestorBankAccNotFound = 2036,
        InvestorHavePendingTemp = 2037,
        InvestorNotFoundOrNotSuitable = 2038,
        InvestorPhoneRegis = 2039,
        InvestorEmailRegis = 2040,
        InvestorErrorOCRIDTypeInvalid = 2041,
        InvestorEkycUpdateNotCmnd = 2042,
        InvestorContactAddressNotFound = 2043,
        InvestorStatusNotT = 2044,
        InvestorNotProf = 2045,
        InvestorErrorOCRFontId = 2046,
        InvestorErrorAgeInvalid = 2047,
        InvestorSetDefaultIdentificationNotConfirm = 2048,
        InvestorNotInRelationshipWithTradingProvider = 2049,
        InvestorVerifyEmailNotFound = 2050,
        InvestorContactAddressNotFound2 = 2051,
        InvsetorVerifyEmailExpired = 2052,
        InvestorEmailAlreadyVerified = 2053,
        InvestorProfRequestPending = 2054,
        InvestorUpdateUserNotEpicOrTradingProvider = 2055,
        InvestorActualNotFound = 2056,
        InvestorReferralCodeNotFound = 2057,
        InvestorReferralCodeIsUsed = 2058,
        InvestorAlreadyUseReferralCode = 2059,
        InvestorRefCodeNotOfSale = 2060,
        InvestorRefCodeNotFound = 2061,
        InvestorNotFoundByRefCodeSelf = 2062,
        InvestorIdTypeDifferenceWithOcrType = 2063,
        InvestorBankAccoutHavingOrder = 2064,
        InvestorIdIsNotVerifiedId = 2065,
        InvestorEmailIsAlreadyVerified = 2066,
        InvestorNotFoundDefaultIdentification = 2067,
        InvestorIdentificationNotVerified = 2068,
        InvestorTempTaxCode = 2069,
        InvestorTempIdNo = 2070,
        InvestorInNotActive = 2071,
        InvestorReferralCodeInUse = 2072,
        InvestorReferralCodeDuplicate = 2073,
        InvestorReferralCodeCanNotNull = 2074,
        InvestorToDoNotFound = 2077,
        InvestorIdExpired = 2078,
        InvestorPhoneNotFound = 2080,
        InvestorCanNotDelExistOrderInvest = 2081,
        InvestorCanNotDelExistOrderGarner = 2082,
        InvestorCanNotDelExistOrderRealEstate = 2083,
        InvestorCanNotDelExistReferraCodeInOrderRst= 2084,
        InvestorCanNotDelExistReferraCodeInOrderGan = 2085,
        InvestorCanNotDelExistReferraCodeInOrderInv = 2086,
        InvestorTooManyRequestIp = 2087,
        InvestorSearchHistoryNotfound = 2088,

        // bond
        BondPolicyIdRequired = 3000,
        TradingProviderNotFound = 3001,
        BondInfoNotFound = 3006,
        BondDepositProviderNotFound = 3011,
        BondOrderNotFound = 3015,
        BondPrimaryNotFound = 3045,
        BondSecondaryNotFound = 3046,
        BondPolicyNotFound = 3055,
        BondPolicyDetailNotFound = 3056,
        BondDitributionContractNotFound = 3060,
        BondOrderCanNotCancel = 3092,
        BondOrderContractFileNotFound = 3108,

        //core
        CorePartnerNotFound = 4003,
        CoreSaleNotFound = 4005,
        CoreReferralCodeNotInTradingProvider = 4006,
        CoreSaleManagerTradingProviderExistWithInvestor = 4049,
        CoreBussinessCustomerNotFound = 4007,
        CoreBusinessCustomerBankNotFound = 4009,
        CoreBusinessCustomerBankOfTradingNotFound = 4010,
        CoreCifCodeNotFound = 4012,
        CoreApproveNotFound = 4024,
        CoreBusinessCustomerBankTempNotFound = 4025,
        CoreBusinessCustomerNotFound = 4007,
        CoreBankNotFound = 4023,
        CoreSaleExistInTradingProvider = 4031,
        CoreSaleIsDeactive = 4037,
        CoreSaleCollabContractNotFound = 4038,
        CoreBusinessCustomerSettingSignPdfNotFound = 4042,
        CoreSignPdfFailed = 4045,
        CoreSignPdfServerNotValid = 4047,
        CoreImageTempNotFound = 4052,
        CoreSaleNotExistInTradingProvider = 4053,
        CoreTradingMSBPrefixAccountNotFound = 4069,
        CoreSaleReferralCodeExistReferralCodeSaleOrder = 4070,
        CoreTradingMSBPrefixAccountIsExist = 4071,
        CoreTradingMSBPrefixAccountNotConfigured = 4072,
        CoreBankBinIsNull = 4073,
        CoreBankNoAndBankIsExists = 4074,
        CoreTradingProviderPartnerRelationshipNotFound = 4075,
        CorePartnerMsbPrefixAccountIsExist = 4076,
        CorePartnerMsbPrefixAccountNotFound = 4077,
        CoreMsbPrefixAccountNotFound = 4078,
        CoreTradingProviderConfigNotExistKey = 4080,
        CoreTradingProviderConfigExistKeyData = 4081,
        CoreInvestorOrderDeliveryCodeNotFound = 4082,
        CoreTradingProviderConfigValueSendNotiInvalid= 4083,
        CorePartnerBankAccountNotFound= 4084,
        CoreSaleStatusIllegal = 4085,
        CoreXvtTokenNotFound = 4086,
        CoreXvtTokenIsExpired = 4087,
        CoreXvtTokenIsNotPermissionExpired = 4088,

        // image & file
        FileExtensionNoAllow = 5001,
        FileNotFound = 5002,
        FileUploadNoContent = 5003,
        FileOverUploadLimit = 5004,
        FileConfigImagePathInValid = 5005,
        FileWordXmlValid = 5006,

        // invest
        InvestProjectNotFound = 6001,
        InvestPolicyTempNotFound = 6009,
        InvestPolicyDetailTempNotFound = 6010,
        InvestPolicyNotFound = 6015,
        InvestOwnerExist = 6017,
        InvestPolicyDetailNotFound = 6019,
        InvestOrderNotFound = 6023,
        InvestDistributionNotFound = 6024,
        InvestContractTemplateNotFound = 6025,
        InvestOrderContractFileNotFound = 6026,
        InvestOwnerNotFound = 6027,
        InvestGeneralContractorNotFound = 6028,
        InvestTotalValueOrderMustBiggerMinMoneyPolicy = 6029,
        InvestProjectTypeNotFound = 6031,
        InvestOrderNotInStatusActive = 6037,
        InvestDistributionIsCloseOrder = 6038,
        InvestPolicyNotActive = 6039,
        InvestConfigContractCodeNotFound = 6057,
        InvestPolicyDetailNotActive = 6040,
        InvestRenewalsRequestNotExist = 6042,
        InvestRenewalsNotFound = 6042,
        InvestWithdrawalNotFound = 6044,
        InvestWithdrawalApproveTooLarge = 6045,
        InvestOrderCanNotDeleteCuzExistPayment = 6048,
        InvestOrderCannotApprove = 6064,
        InvestOrderApproveCheckTotalValue = 6065,
        InvestInterestPaymentNotFound = 6058,
        InvestInterestPaymentPayDateLargerNowDate = 6059,
        InvesInterestPaymentApproveExistRenewalRequest = 6060,
        InvesOrderRenewalRequestNotExist = 6061,
        InvestWithdrawalNotInRequest = 6062,
        InvesInterestPaymentNotRequest = 6063,
        InvestOrderTotalValueBiggerMaxMoney = 6066,
        InvestWithdrawalIdNotInPrepareDetail = 6068,
        InvestRequestIsNotTheSameDistribution = 6069,
        InvestRenewalRequestExpired = 6071,
        InvestInterestPaymentIdNotInPrepareDetail = 6072,
        InvestOrderExcceedRemailLimitDistribution = 6073,
        InvestOrderPaymentNotFound = 6077,
        InvestOrderDeliveryStatusDelivered = 6079,
        InvestOrderStatusIsNotActive = 6080,
        InvestProjectInformationShareNotFound = 6081,
        InvestProjectTradingProviderCanNotDelete = 6082,
        InvestProjectTotalInvestmentCanNotUpdate = 6083,
        InvestOrderInterstPaymentRequestExist = 6085,
        InvestOrderWithdrawalRequestExist = 6086,
        InvestOrderStatusUpdateInvalid = 6087,
        InvestOrderTotalValueBiggerPolicyMaxMoney = 6088,
        InvestCalenderNotFound = 6089,
        InvestOrderApproveCuzPolicyDeactive = 6090,
        InvestOrderContractFileIsCreating = 6091,
        InvestContractFileIsRequeired = 6092,
        InvestPolicyDetailExistInterestPayment = 6093,
        InvestPolicyDetailExistWithdrawal = 6094,

        // company share
        CpsInfoNotFound = 7001,
        CpsSecondaryNotFound = 7002,
        CpsOrderPaymentTradingProviderId = 7005,
        CpsOrderPaymentNotFound = 7006,
        CpsOrderNotFound = 7007,
        CpsOrderPaymentApproveDateFuture = 7008,
        CpsPolicyNotFound = 7009,
        CpsPolicyDetailNotFound = 7010,
        CpsContractTemplateNotFound = 7026,
        CpsOrderContractFileNotFound = 7027,

        //garner
        GarnerProductNotFound = 8001,
        GarnerApproveNotFound = 8002,
        GarnerDistributionNotFound = 8003,
        GarnerPolicyNotFound = 8004,
        GarnerPolicyDetailNotFound = 8005,
        GarnerProductTradingProviderTotalInvestmentSubTooLong = 8006,
        GarnerProductTradingProviderQuantityTooLong = 8007,
        GarnerPolicyTempNotFound = 8008,
        GarnerPolicyDetailTempNotFound = 8009,
        GarnerOrderPaymentNotFound = 8010,
        GarnerOrderPaymentApproveDateFuture = 8011,
        GarnerOrderDeliveryStatusDelivery = 8012,
        GarnerOrderDeliveryStatusReceived = 8013,
        GarnerOrderDeliveryStatusDone = 8014,
        GarnerContractTemplateTempNotFound  = 8015,
        GarnerContractTemplateNotFound  = 8016,
        GarnerFileExtensionNoAllow = 8017,
        GarnerDistributionIsClose = 8018,
        GarnerOrderPaymentTradingBankAcc = 8019,
        GarnerFileContractPdfNotFound = 8020,
        GarnerDistributionTradingBankAccNotFound = 8021,
        GarnerOrderNotFound = 8023,
        GarnerOrderCanNotApprove = 8025,
        GarnerOrderApproveCheckTotalValue = 8026,
        GarnerOrderPolicyStatusDeativate = 8027,
        GarnerOrderPolicyDetailStatusDeativate = 8028,
        GarnerOrderCheckTotalValue = 8030,
        GarnerPolicyDetailByDateNotFound = 8031,
        GarnerOrderActiveDateGreaterThanNow = 8032,
        GarnerOrderActiveDateGreaterThanLastPay = 8033,
        GarnerOrderInvestDateIsNull = 8034,
        GarnerOrderContractFileNotFound = 8037,
        GarnerCalenderNotFound = 8035,
        GarnerOrderWithdrawalNotFound = 8036,
        GarnerOrderContractTempWordNotFound = 8038,
        GarnerOrderContractTempPdfNotFound = 8039,
        GarnerOrderContractSignatureNotFound = 8040,
        GarnerOrderContractScanNotFound = 8041,
        GarnerOrderNotInStatusCancel = 8044,
        GarnerPolicyIsUsingInOrder = 8042,
        GarnerPolicyDetailIsUsingInOrder = 8043,
        GarnerOrderWithdrawIsRequest = 8045,
        GarnerInterestPaymentNotFound = 8046,
        GarnerProductDuplicateCode = 8047,
        GarnerDistributionNotCofigContractCode = 8049,
        GarnerCofigContractCodeNotExistValue = 8050,
        GarnerOrderStatusNotInitialState = 8048,
        GarnerConfigContractCodeNotFound = 8051,
        GarnerWithdrawalNotContaintDetail = 8052,
        GarnerWithdrawalNotInRequest = 8053,
        GarnerProductPriceNotFoundDate = 8054,
        GarnerWithdrawAmountIsMoreThanTotalValue = 8055, // số tiền rút đang lớn hơn số tiền đầu tư
        GarnerOrderStatusIsActive = 8056,
        GarnerRequestIsNotTheSameDistribution = 8057,
        GarnerWithdrawalNotFound = 8058,
        GarnerContractTemplateTempExist = 8059,
        GarnerWithdrawalStatusBankNotInit = 8060,
        GarnerWithdrawalStatusNotApprovePay = 8061,
        GarnerWithdrawalIdNotInPrepareDetail = 8062,
        GarnerOrderLimitMaxMoney = 8063,
        GarnerApproveOrderLimitMaxMoney = 8064,
        GarnerBlockadeLiberationNotFound = 8065,
        GarnerReceiveContractTemplateNotFound = 8066,
        GarnerOrderExistPaymentNotDeleted = 8067,
        GarnerOrderHasDeliveryCodeNotFound = 8068,
        GarnerDistributionPolicyFileNotFound = 8069,
        GarnerOrderStatusIsNotActive = 8070,
        GarnerInterestPaymentNotInRequest = 8071,
        GarnerInterestPaymentNotContaintDetail = 8072,
        GarnerOrderCheckTotalValueBiggerMaxMoneyPolicy = 8073,
        GarnerOrderExcceedRemailLimitDistribution = 8074,
        GarnerInterestPaymentNotFoundFirstOrderByPolicy = 8075,
        GarnerOrderDeliveryStatusDelivered = 8076,


        //Payment
        PaymentRequestNotFound = 9001,
        PaymentRequestDetailNotFound = 9002,
        PaymentMsbNotificationNotFound = 9003,
        PaymentMsbNotificationExistRequestNotSuccess = 9004,
        PaymentMsbNotificationCanNotCancel = 9005,

        //Real Estate
        RstOwnerNotFound = 10001,
        RstOwnerExist = 10002,
        RstProjectNotFound = 10003,
        RstApproveNotFound = 10004,
        RstProjectPolicyNotFound = 10005,
        RstConfigContractCodeNotFound = 10006,
        RstSellingPolicyNotFound = 10007,
        RstProjectDistributionPolicyNotFound = 10008,
        RstContractTemplateTempNotFound = 10009,
        RstProjectUtilityNotFound = 10010,
        RstProjectUtilityMediaNotFound = 10011,
        RstBuildingDensityTypesNotCorrect = 10012,
        RstProjectStructureNotFound = 10013,
        RstProjectUtilityExtendNotFound = 10014,
        RstProjectFileNotFound = 10015,
        RstProductItemNotFound = 10016,
        RstProjectUtilityIsNotSelected = 10017,
        RstProjectMediaNotFound = 10018,
        RstProjectMediaExtensionFileNotCorrect = 10019,
        RstDistributionNotFound = 10020,
        RstDistributionProductItemNotFound = 10021,
        RstProjectMediaDetailNotFound = 10022,
        RstDistributionPolicyNotFound = 10023,
        RstProductItemMediaNotFound = 10024,
        RstProductItemMediaDetailNotFound = 10025,
        RstDistributionContractTemplateNotFound = 10026,
        RstOpenSellNotFound = 10027,
        RstOpenSellDetailNotFound = 10028,
        RstOpenSellDetailIsExistDistributionItem = 10029,
        RstDistributionCanNotPause = 10030,
        RstDistributionItemCanNotDelete = 10031,
        RstOpenSellCanNotPause = 10032,
        RstProjectPolicyIsNotSelected = 10033,
        RstProductItemPolicyNotFound = 10034,
        RstProductItemUtilityNotFound = 10035,
        RstSellingPolicyIsNotSelected = 10036,
        RstOpenSellFileNotFound = 10037,
        RstOpenSellContractTemplateNotFound = 10038,
        RstDistributionCanNotDelete = 10039,
        RstProjectNotYetDistributionForTrading = 10040,
        RstCartNotFoundByInvestor = 10041,
        RstOrderNotFound = 10042,
        RstOrderStatusNotInitialState = 10043,
        RstOrderExistPaymentNotDeleted = 10044,
        RstDistributionNotInTrading = 10045,
        RstDistributionProductItemNotActive = 10046,
        RstOpenSellNotInTrading = 10047,
        RstProductItemInTrading = 10048,
        RstDistributionPolicyNotActive = 10049,
        RstOrderPaymentTradingBankAcc = 10050,
        RstOrderPaymentNotFound = 10051,
        RstCartExistOpenSellDetail = 10052,
        RstOpenSellCanNotDelete = 10053,
        RstOpenSellDetailExistTrading = 10054,
        RstOrderCoOwnerNotFound = 10055,
        RstProductItemExistInDistributionOfTradingProvider = 10056,
        RstDistributionProductItemHaveTrading = 10057,
        RstOpenSellBankTradingNotFound = 10058,
        RstDistributionBankPartnerNotFound = 10059,
        RstOpenSellCanNotApproveOpenSellBankNotExist = 10060,
        RstOrderPaymentCanNotDelete= 10061,
        RstOrderPaymentCanNotApproveCuzProductItemHold = 10062,
        RstOrderCanNotApproveCuzDistributionProductItemLock = 10063,
        RstOrderCanNotApproveCuzProductItemStatus = 10064,
        RstOrderCanNotApproveOrderStatusInValid = 10065,
        RstOrderCanNotApproveDepositMoneyNotEqual = 10066,
        RstOpenSellDetailLockInDistributionItem = 10067,
        RstOpenSellDetailStatusLock = 10068,
        RstOpenSellDetailStatusTrading = 10069,

        RstOrderPaymentBankIsNotEmpty = 10070,
        RstProductItemCanNotLockCuzStatusTrading = 10071,
        RstOpenSellDetailCanNotLockCuzStatusTrading = 10072,
        RstOrderPaymentCanNotInsertCuzProductItemStatusInvalid = 10073,
        RstOpenSellDetailLockByTradingProvider = 10074,
        RstOpenSellDetailLockByPartner = 10075,
        RstOrderPaymentCanNotApproveCuzProductItemLockNotOfOrder = 10076,
        RstOrderStatusBlockadeCanNotOperation = 10077,
        RsProjectFavouriteNotFound = 10078,
        RstCartOpenSellDetailStatusNotSelling = 10079,
        RstDistributionPolicyTypeDissimilarity = 10080,
        RstDistributionPolicyLockBiggerDeposit = 10081,
        RstOrderCannotExtendedKeepTime = 10082,
        RstOrderCannotExtendedKeepTimeProductItemNotGiuCho = 10083,
        RstProjectInformationShareNotFound = 10084,
        RstProjectCanNotDelete = 10085,
        RstProductItemDesignDiagramFileNotFound = 10086,
        RstProductItemMaterialFileNotFound = 10087,
        RstProductItemMaterialFileIsExist = 10088,
        RstProductItemDesignDiagramFileIsExist = 10089,

        // Voucher
        LoyVoucherStartDateLargerThanExpiredDate = 11001,
        LoyVoucherNotFound = 11002,
        LoyVoucherDescriptionContentTypeRequired = 11003,
        LoyVoucherCanNotDeleteBecauseHaveVoucherInvestor = 11004,
        LoyVoucherHisAccumulatePointNotFound = 11005,
        LoyRankNotFound = 11006,
        LoyRankPointRangeOverride = 11007,
        LoyRankPointStartMustLessThanPointEnd = 11008,
        LoyAccumulatePointNotEnough = 11009,
        LoyVoucherEndDateMustLessThanExpiredDate = 11010,
        LoyPointInvestorNotFound = 11011,
        LoyRedemptionPointExceeded = 11012,
        LoyConversionPointNotFound = 11013,
        LoyConversionPointStatusInvalid = 11014,
        LoyVoucherConversionIsOverLimit = 11015,
        LoyLuckyProgramNotFound = 11016,
        LoyLuckyScenarioNotFound = 11017,
        LoyLuckyScenarioDetailSumProbabilityInvaid = 11018,
        LoyLuckyProgramInvestorNotFound = 11019,
        LoyLuckyScenarioTypeLuckySpinExist = 11020,
        LoyLuckyProgramInvestorExceedNumberOfTurn = 11021,
        LoyLuckyProgramInvestorNotYetStartTurn = 11022,
        LoyLuckyProgramInvestorTimeUpTurn = 11023,
        LoyLuckyProgramInvestorCanNotDelCuzIsJoin= 11024,

        //Event
        EvtEventNotFound = 12000,
        EvtEventDetailNotFound = 12001,
        EvtConfigContractCodeNotFound = 12002,
        EvtEventStatusNotValid = 12003,
        EvtTicketNotFound = 12004,
        EvtEventMediaNotFound = 12005,
        EvtEventMediaDetailNotFound = 12006,
        EvtTicketMediaNotFound = 12007,
        EvtOrderPaymentBankIsNotEmpty = 12008,
        EvtOrderPaymentNotFound = 12009,
        EvtOrderPaymentCanNotDelete = 12010,
        EvtOrderPaymentApproveDateFuture = 12011,
        EvtOrderNotFound = 12012,
        EvtOrderReceiveHardTicketNotFound = 12013,
        EvtOrderRequestReceiveReciptNotFound = 12014,
        EvtTicketIsInUse = 12015,
        EvtOrderNotDelete = 12016,
        EvtOrderTicketScanError = 12017,
        EvtOrderCanNotAppove = 12018,
        EvtOrderTicketNotFound = 12019,
        EvtOrderTicketCannotScanByPermission = 12020,
        EvtOrderTicketNotLock = 12021,
        EvtOrderTicketLock = 12022,
        EvtEventDescriptionMediaNotFound = 12023,
        EvtTicketsSoldOut = 12026,
        EvtEventIsNotActive = 12024,
        EvtTicketIsPastTheEventTime = 12025,
        EvtOrderCanNotDeleteBecauseHavePayment = 12027,
        EvtAdminEventNotFound = 12028,
        EvtTicketCodeQRNotValid = 12029,
        EvtEventTooLateToJoin = 12030,
        EvtTicketHasBeenUsed = 12031,
        EvtOrderIsNotValid = 12032,
        EvtEventDetailIsNotValid = 12033,
        EvtEventDetailNotStart = 12034,
        EvtEventDetailNotActive = 12035,
        EvtEventNotOpen = 12036,
        EvtOrderInvoiceRequestVaild = 12037,
        EvtOrderTicketRequestVaild = 12038,
        EvtTicketTemplateActiveNotFound = 12039,
        EvtDeliveryTicketTemplateActiveNotFound = 12040,
        EvtOrderContractAddressNotNull = 12041,
        EvtOrderPaymentNotUpdate = 12042,
        EvtEventAdminExists = 12043,
        EvtOrderCanNotUpdateBecauseHavePayment = 12044,
        EvtOrderTicketUrlIsCreating = 12045,
    }

    public static class ErrorMessage
    {
        public static Dictionary<int, string> ErrorMessages = new Dictionary<int, string>();

        public static string Get(int errorCode)
        {
            ErrorMessages.TryGetValue(errorCode, out string message);
            return message ?? "no message";
        }
    }
}
