version: '3.4'

services:
  epic.apigateway:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5003
    image: ${DOCKER_REGISTRY-}epicapigateway
    build:
      context: .
      dockerfile: EPIC.APIGateway/EPIC.APIGateway/Dockerfile
    ports:
        - 8089:5003
